import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
    title: "Sobre nós | Ajudai_",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <main>
            <section className="flex items-center px-36 py-12">
                <div>
                    <h1 className="font-bold text-4xl">Sobre nós</h1>
                    <p className="mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac orci molestie ligula gravida efficitur in eget justo.</p>
                </div>
                <Image src="https://via.placeholder.com/453x453" className="rounded" alt="32x32" width={453} height={453}/>
            </section>

            <section className="flex justify-center items-center gap-14 bg-zinc-200 px-36 py-12">
                <Image src="https://via.placeholder.com/453x453" className="rounded" alt="32x32" width={453} height={453}/>

                <div>
                    <h2 className="font-bold text-4xl">Lorem ipsum dolor sit amet</h2>
                    <p className="mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac orci molestie ligula gravida efficitur in eget justo.</p>
                </div>
            </section>

            <section className="flex items-center px-36 py-12">
                <div>
                    <h1 className="font-bold text-4xl">Sobre nós</h1>
                    <p className="mt-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ac orci molestie ligula gravida efficitur in eget justo.</p>
                </div>
                <Image src="https://via.placeholder.com/453x453" className="rounded" alt="32x32" width={453} height={453}/>
            </section>
        </main>
    )
}