import { Button } from "@/components/button";
import { Card } from "@/components/Card";
import { Heart, Sparkle, UsersFour } from "@/utils/icons";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Início | Ajuda aí",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex flex-col gap-12">
      <section className="px-36 py-12">
        <div className="flex items-center justify-between gap-12 max-w-7xl w-full mx-auto">
          <div>
            <h1 className="font-bold text-4xl">Ajuda aí<br/>Sempre ajudando ao proximo</h1>
            <p className="mt-2">O Ajuda aí é uma plataforma dedicada à troca e doação de mantimentos, móveis e outros itens necessários para aqueles que sofreram com desastres naturais. Além disso, oferece um espaço onde as comunidades podem procurar e se conectar com voluntários dispostos a ajudar</p>
            <div className="flex gap-2 mt-5">
              <Link className="px-5 py-2 bg-pelorous-600 text-white rounded-md" href="/signup">Cadastre sua ONG</Link>
              <Link className="px-5 py-2 bg-affair-700 text-white rounded-md" href="/help-ong">Ajude uma ONG</Link>
            </div>
          </div>

          <Image src="/recolhendo_doacoes.svg" className="rounded" title="Imagem de colaboradores recolhendo caixas" alt="Imagem de colaboradores recolhendo caixas" width={453} height={453}/>
        </div>
      </section>

      <section className="bg-purple-50 px-36 py-12">
        <div className="flex justify-center items-center gap-14 max-w-7xl w-full mx-auto">
          <Image src="/doacoes.svg" className="rounded" title="Foto de sacolas vermelhas e cianas cheia de doações" alt="Foto de sacolas vermelhas e cianas cheia de doações" width={453} height={453}/>

          <div>
            <h2 className="font-bold text-affair-600 text-4xl">Valores</h2>
            <p className="mt-2">Os valores do Ajuda aí refletem o compromisso da plataforma com a solidariedade, a eficácia e a empatia. Aqui estão os valores principais que orientam nossa missão e operações:</p>
          </div>
        </div>
      </section>

      <section className="px-36 py-12 max-w-7xl w-full mx-auto">
        <h2 className="font-bold text-4xl text-pelorous-600 text-center mb-5">Nossa Missão</h2>

        <div className="flex gap-5">
          <Card.Root className="w-72">
            <Card.Header className="items-center justify-center pt-8">
              <Heart className="text-pelorous-600" size={44} weight="fill"/>
            </Card.Header>
            <Card.Content className="pb-12 mt-5">
              <p className="text-center">Permitir um ambiente de colaboração e reconhecimento<br /> entre ONGs</p>
            </Card.Content>
          </Card.Root>

          <Card.Root className="w-72">
            <Card.Header className="items-center justify-center pt-8">
              <Sparkle className="text-yellow-400" size={44} weight="fill"/>
            </Card.Header>
            <Card.Content className="pb-12 mt-5">
              <p className="text-center">Mostrar ONGs perto de você que fazem a diferença na<br /> comunidade</p>
            </Card.Content>
          </Card.Root>

          <Card.Root className="w-72">
            <Card.Header className="items-center justify-center pt-8">
              <UsersFour className="text-affair-600" size={44} weight="fill"/>
            </Card.Header>
            <Card.Content className="pb-12 mt-5">
              <p className="text-center">Fortalecer a atuação e impacto das ONGs,<br /> principalmente em momentos de crise</p>
            </Card.Content>
          </Card.Root>
        </div>
      </section>

      <section className="bg-teal-100 px-36 py-12">
        <div className="flex justify-center items-center gap-14 max-w-7xl w-full mx-auto">
          <div>
            <h2 className="font-bold text-4xl text-pelorous-600">Contato</h2>
            <p className="mt-2">Visite nosso site e preencha o formulário de contato para qualquer pergunta ou solicitação: Estamos aqui para ajudar e responder suas dúvidas! Não hesite em nos contatar para qualquer necessidade ou informação adicional.</p>
            <Button label="Entrar em contato" className="bg-pelorous-600 text-white mt-2"/>
          </div>

          <Image src="/criancas_brinquedos.png" alt="Foto de duas crianças em uma loja de brinquedos" className="rounded" width={453} height={453}/>
        </div>
      </section>
    </main>
  );
}
